### ISSUE TITLE
Integrate with sqlite-zstd

### ISSUE THREAD

**Issue by franchb** [ncruces/go-sqlite3#105]
Is it possible to add [sqlite-zstd](https://github.com/phiresky/sqlite-zstd) extension to `ncruces/go-sqlite3` WASM driver?

**Comment by ncruces** [comment]
Maybe, but it really depends on what you mean.

Any extension you can compile and statically link into your own Wasm, is probably fair game.

I can't give specific instructions for [sqlite-zstd](https://github.com/phiresky/sqlite-zstd), but you can check how `sqlite3.wasm` is [built](https://github.com/ncruces/go-sqlite3/blob/main/embed/build.sh), and how various extensions are [linked and initialized](https://github.com/ncruces/go-sqlite3/blob/main/sqlite3/main.c). Then it's just a matter of [using your own Wasm](https://pkg.go.dev/github.com/ncruces/go-sqlite3#pkg-variables).

If, however, want you _really_ want is readonly compressed databases, my suggestion is that you compress your entire database with [Zstandard Seekable Format](https://github.com/facebook/zstd/blob/dev/contrib/seekable_format/zstd_seekable_compression_format.md), and use [zstd-seekable-format-go](https://github.com/SaveTheRbtz/zstd-seekable-format-go) with the [reader VFS](https://pkg.go.dev/github.com/ncruces/go-sqlite3/vfs/readervfs).

**Comment by franchb** [comment]
Thank you! I'll give [zstd-seekable-format-go](https://github.com/SaveTheRbtz/zstd-seekable-format-go) a shot.

**Comment by ncruces** [comment]
Please report any feedback!
