### ISSUE TITLE
Launching the SQLite shell

### ISSUE THREAD

**Issue by daenney** [ncruces/go-sqlite3#110]
One nice benefit of this library is that there's no need for the target system to have sqlite installed, but as such the `sqlite3` CLI will also be absent.

I've been looking at if it's possible to invoke the sqlite shell from this library, with the idea of embedding that as a subcommand in my own CLI. But I don't think that's possible currently?

**Comment by ncruces** [comment]
No, the SQLite shell is not a library, but an entire additional code base using the library.

I could, potentially, compile it to WASI but:
- as Wasm (much like Go) works best with static linking, it'll be another binary larger than the current one.
- I'd need to modify it somewhat if I wanted my VFS (OS layer) coupled with the shell; I could use the Unix VFS with WASI, but there'd be no file locking (dangerous) and no shared memory WAL.
- just “compile to WASI” doesn't necessarily solve _shell_ like completion, and command history; `stdin` is a very special file when attached to a shell; I don't know how good wazero is here.

So there are challenges, this is a project on its own. If you're interested, I definitely wouldn't stop anyone from working on it; I'll be as helpful as possible.

But I suspect static linking the shell with musl might be more productive/satisfying? I'd investigate the zig toolchain for cross compilation.

**Comment by daenney** [comment]
Right yeah, that makes sense. Hadn't thought of using the zig toolchain, but that's a good point.

I'll fiddle around with it at some point and see if I can get anywhere.
