### ISSUE TITLE
Custom time and implementing sql.Scanner

### ISSUE THREAD

**Issue by daenney** [ncruces/go-sqlite3#132]
I ran into a slightly confusing behaviour when implementing `sql.Scanner` for a custom time struct.

I opened a DB using the database/sql driver with a table that has a column of type `TEXT` storing RFC3339 timestamps. I add `_timefmt=rfc3339` to ensure a consistent format is written and read when inserting from or scanning to a `time.Time`.

However, with a lot of APIs I end up needing some custom time type, so I fairly often have:

```go
type myTime struct { time.Time }
```

You can have to implement `Scan(value any) error`. Since it's stored in a `TEXT` field I made the assumption I'd get something string-y back and so the first thing I did was `driver.String.ConvertValue(value)`. This results in a string of the time, but it's not the string as stored in the DB because the driver already caught on to this and converted it to a `time.Time` object because of `maybeTime` (I think?).

So when looking into it, I hit the `return `fmt.Sprintf(...)` case of `driver.String.ConvertValue`:

```go
func (stringType) ConvertValue(v any) (Value, error) {
	switch v.(type) {
	case string, []byte:
		return v, nil
	}
	return fmt.Sprintf("%v", v), nil
}
```

Then trying to parse that value with `time.RFC3339` as the layout blew up, because the `%v` formatting of a `time.Time` is done with a different layout.

Having experimented a bit, it seems that in this case I can get either a `time.Time` if the driver recognised the time format and converted it, or a string if it didn't (for example some other process wrote into that column without the right format). This means that when implementing `sql.Scanner` on a custom time struct you need to do a type switch first thing. I'm thinking it may be worthwhile to document that, maybe with an example, for the driver package?

**Comment by ncruces** [comment]
Yes, `maybeTime` is likely the culprit.

I need to consider the code paths, and yes, likely documentation (and an example) is the best way to deal with this.

For context, `maybeTime` is my best attempt at respecting SQLite's "dynamic typing" ethos: `time.Time` is stored as RFC3339 `TEXT`, but is magically recovered as either a `string` or `time.Time` (or `[]byte`, or...).

The way that's done is that I parse and use a `time.Time` if (and only if) it round-trips back to the exact same `string` (so that nothing is lost).

I didn't consider `sql.Scanner` here, unfortunately.

**Comment by ncruces** [comment]
About `_timefmt`, unless you're typing your columns as `DATE`, `TIME`, `DATETIME`, or `TIMESTAMP` (so `STRICT` tables are out), the default is the same as `_timefmt=rfc3339`.

**Comment by daenney** [comment]
> About `_timefmt`, unless you're typing your columns as `DATE`, `TIME`, `DATETIME`, or `TIMESTAMP` (so `STRICT` tables are out), the default is the same as `_timefmt=rfc3339`.

Ah, yeah. I always have my tables set to `STRICT`. It would be nice if stuff like `DATETIME` worked as aliases in `STRICT` mode too because their self-documenting nature is kinda nice. But alas.
