### ISSUE TITLE
Understanding WAL support

### ISSUE THREAD

**Issue by michaellenaghan** [ncruces/go-sqlite3#153]
Hello…

I’m trying to understand the implications of the VFS implementation on WAL support.

I’m developing on macOS and deploying to FreeBSD. 

I’d like to keep the option of deploying to Linux open.

I think I can meet the “single process” requirement by, for example, having the web server perform its own scheduled backups.

It sounds like I should expect WAL to work in my case, but I’m not sure?

And if it does, are there other things I should know or consider?

Thank you,
Michael

**Comment by ncruces** [comment]
Yes, that's it, as long as a single process opens the database, everything should work. Other processes are locked out with `SQLITE_PROTOCOL`, so there's little risk of data corruption. Things like [Litestream](https://litestream.io/) won't work, though.

If you're developing on macOS, you may want to run (some/all) tests with the `sqlite3_flock` build tag to better emulate BSD on macOS.

Make sure to use the latest version, as [`v0.18.1`](https://github.com/ncruces/go-sqlite3/releases/tag/v0.18.1) included an important fix for BSD.

**Comment by michaellenaghan** [comment]
Excellent, thank you, and thank you for the suggestions.
