### ISSUE TITLE
In-memory databases don't seem to be shareable across connections

### ISSUE THREAD

**Issue by michaellenaghan** [ncruces/go-sqlite3#156]
SQLite's [In-Memory Databases](https://sqlite.org/inmemorydb.html) page explains how to share an in-memory database across connections:

> However, the same in-memory database can be opened by two or more database connections as follows:
>
>     rc = sqlite3_open("file::memory:?cache=shared", &db);
>
> ... This allows separate database connections to share the same in-memory database.

The `gormlite` test code has an example of such a URI, [here](https://github.com/ncruces/go-sqlite3/blob/6101debe28367537a027051b842f86f948a0efc5/gormlite/error_translator_test.go#L12).

But as far as I can tell, opening connections that way a) doesn't generate an error; and b) doesn't share the database.

If I use exactly the same URI as the `gormlite` test, `"file:testdatabase?mode=memory&cache=shared"`, to open two connections, and create a table in one of them, the table isn't visible to the other connection.

I didn't know if that was expected or surprising, so I thought I'd pass it along. 

(I see that there's a `memdb` VFS, and that it does in fact support multiple connections. Maybe this explains why it's there? :-)

**Comment by ncruces** [comment]
See https://github.com/ncruces/go-sqlite3/discussions/97.

That test is [copied over from elsewhere](https://github.com/ncruces/go-sqlite3/blob/6101debe28367537a027051b842f86f948a0efc5/gormlite/download.sh#L13C11-L13C89), but I'll change it anyway.
