### ISSUE TITLE
"memory" database breaks data consistency

### ISSUE THREAD

**Issue by wxiaoguang** [ncruces/go-sqlite3#186]
Demo, it fails:

```
package gosqlite3

import (
	"database/sql"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"strconv"
	"sync"
	"testing"

	_ "github.com/ncruces/go-sqlite3/driver"
	_ "github.com/ncruces/go-sqlite3/embed"
)

func TestGoSqlite3(t *testing.T) {
	var version string
	//db, _ := sql.Open("sqlite3", "file:demo.db") // real file works
	db, _ := sql.Open("sqlite3", "file::memory:") // memory database fails
	db.QueryRow(`SELECT sqlite_version()`).Scan(&version)
	println(version)

	_, err := db.Exec("DROP TABLE IF EXISTS test")
	require.NoError(t, err)

	_, err = db.Exec("CREATE TABLE test (id INTEGER PRIMARY KEY, k TEXT, v TEXT)")
	require.NoError(t, err)

	_, err = db.Exec("INSERT INTO test (k,v) VALUES ('a', 1)")
	require.NoError(t, err)

	testQuery := func(t *testing.T) {
		var v int
		db.QueryRow(`SELECT v FROM test`).Scan(&v)
		assert.Equal(t, 1, v)
	}

	testQuery(t)

	var wg sync.WaitGroup
	for i := 0; i < 10; i++ {
		wg.Add(1)
		go t.Run("Test-"+strconv.Itoa(i), func(t *testing.T) {
			defer wg.Done()
			testQuery(t)
		})
	}
	wg.Wait()
}
```

![image](https://github.com/user-attachments/assets/bd3810ea-4866-480a-a2a5-4fa7934d7025)

**Comment by ncruces** [comment]
No SQLite library anywhere lets you share a `:memory:` database across threads.

See https://github.com/ncruces/go-sqlite3/discussions/97

**Comment by wxiaoguang** [comment]
> No SQLite library anywhere lets you share a `:memory:` database across threads.
> 
> See #97

But I didn't put `cache=shared` there. So I guess it doesn't "share" the memory database across threads?

**Comment by ncruces** [comment]
Right. So a bunch of threads (goroutines in this case) will fail with table doesn't exist, because they get an empty database instead of the one you setup above.

You'd have figured this out if you printed the error message from `QueryRow(…).Scan(…)`.

**Comment by wxiaoguang** [comment]
It seems somewhat misleading. SQLite only declares it shouldn't use `cache=shared`, but it doesn't say `:memory:` can't be used? 

Or, should it update the README or add some FAQ ..... it seems that many people have been in this situation.

**Comment by ncruces** [comment]
This is common to all Go drivers. See:
https://stackoverflow.com/a/77150429

**Comment by wxiaoguang** [comment]
Hmm, I see, it is actually caused by the connection pool manged by Golang SQL driver.

I proposed a PR to update the readme to clarify the problem:  Update readme to clarify the "memory database" problem #187 (to help other developers to get rid of the memory database trap)  , does it look good to you?
