### ISSUE TITLE
Add ColumnTypeScanType to driver

### ISSUE THREAD

**Issue by ncruces** [ncruces/go-sqlite3#198]
See #197. Continuing here @ngocphuongnb.

For `modernc` you can get new types everytime you call `ColumnTypes()`, and if you call it before the first row, results are undefined. Is this acceptable behavior?

If it isn't, and we really want the type of the column, would it be reasonable to only support this for `STRICT` tables? For those it's totally doable, but some types are impossible (like time, booleans, etc).

If I go by affinity, I'm mostly worried about columns I say are `float64` and there's suddenly a `TEXT`/`BLOB` in them, and `int64` that have fractional numbers. Both can happen, not that it's great database design. Still the affinity rules are complicated: `FLOATING POINT` has `INTEGER` affinity is one example.

I could go with a subset of stricter type names, and argue if you're violating those, your data model sucks. But I really want to test failure modes before commiting.

**Comment by ncruces** [comment]
Branch [`metadata`](https://github.com/ncruces/go-sqlite3/compare/metadata) will have stuff related to this.

**Comment by ngocphuongnb** [comment]
@ncruces I apologize for being busy lately and only having some free time on the weekends. Here’s a minimal example:
```
package main

import (
	"database/sql"
	"reflect"

	_ "github.com/ncruces/go-sqlite3/driver"
	_ "github.com/ncruces/go-sqlite3/embed"
)

var version string

type SQLColumnType interface {
	ScanType() reflect.Type
	DatabaseTypeName() string
}

type Entity map[string]any

func main() {
	db, _ := sql.Open("sqlite3", "file:demo.db")
	result, err := Query[Entity](db, `SELECT 55555 as count`)
}

func Query[T any](db *sql.DB, query string, args ...any) (rows []T, err error) {
	sqlRows, err := db.Query(query, args...)
	if err != nil {
		return nil, err
	}

	for sqlRows.Next() {
		columns, err := sqlRows.Columns()
		if err != nil {
			return nil, err
		}

		values := make([]any, len(columns))
		for i := range columns {
			values[i] = new(any)
		}

		if err := sqlRows.Scan(values...); err != nil {
			return nil, err
		}

		// Perform further conversion from values to T
	}

	return rows, nil
}
```
As shown above, without actual column type information from rows.ColumnTypes(), we are forced to create a slice of generic values, like values := make([]any, len(columns)), to scan the row data.

The SQLite driver already knows the types of the values being queried, so scanning them into any seems inefficient and unclear. If ColumnTypes could provide the type information, the values slice preparation would be much cleaner and more type-safe.

**Comment by ngocphuongnb** [comment]
@ncruces Apologies, I didn’t realize you had already created https://github.com/ncruces/go-sqlite3/pull/199. I’ll update my project to use the latest version and check if all the tests pass.
Thank you for your hard work and dedication, it’s greatly appreciated!
