### ISSUE TITLE
"multiple statements" when only one statement is provided

### ISSUE THREAD

**Issue by bleonard252** [ncruces/go-sqlite3#201]
In a fresh module, with `main.go`:
```go
package main

import (
	"database/sql"
	"log"

	_ "github.com/ncruces/go-sqlite3/driver"
	_ "github.com/ncruces/go-sqlite3/embed"
)

const CREATE_MIGRATION_STATE_TABLE = `
CREATE TABLE IF NOT EXISTS __northwood_migration_state (
	id INT PRIMARY KEY,
	latest_migration INT
);
INSERT INTO __northwood_migration_state (id, latest_migration)
	VALUES (0, 0);
`
const UPDATE_MIGRATION_STATE_MYSQL = `
UPDATE __northwood_migration_state 
	SET latest_migration = ?
	WHERE id = 0;
`

func main() {
	db, err := sql.Open("sqlite3", "database.sqlite")
	if err != nil {
		log.Fatalf("Could not open database: %v", err)
	}
	defer db.Close()
	_, err = db.Exec(CREATE_MIGRATION_STATE_TABLE)
	if err != nil {
		log.Fatalf("Could not create table: %v", err)
	}
	_, err = db.Exec(UPDATE_MIGRATION_STATE_MYSQL, 1)
	if err != nil {
		log.Fatalf("Could not update state: %v", err)
	}
}
```

I get the output:
```
Could not update state: sqlite3: multiple statements
```

Additional information:
* Go version: 1.23.2
* Linux
* This driver, as of issue creation time, is up-to-date.

What's going wrong here? The update SQL only has one statement!

**Comment by ncruces** [comment]
To solve your issue immediately, I think it is enough to remove the semicolon after the `UPDATE` statement.

This will make SQLite consume the whitespace after it and fix the issue.

I understand this is confusing. I had code to consume some of the whitespace (but not comments, for example).

**Comment by ncruces** [comment]
The commit above should fix this. The fact that I had to create that complicated a whitespace parser, and it **still** isn't _bug-for-bug_ compatible with SQLite, shows why I didn't want to do this in the first place. Thank god for fuzzing.

**Comment by bleonard252** [comment]
> To solve your issue immediately, I think it is enough to remove the semicolon after the `UPDATE` statement.
I actually tried this, and it didn't do anything.

Somehow, though, upgrading from 0.21.0 to 5ed4a6c fixed it! Thank you so much!

**Comment by ncruces** [comment]
Yeah, it was meant to. I went through and did my best, as I understand it's confusing. But it requires a parser, and I'm always weary of those. If it wasn't for the fuzzer holding my hand, and running 100M tests on the result I wouldn't have done it.
