### ISSUE TITLE
"sqlite3: disk I/O error" in Linux 2.6.36.4brcmarm armv7l. Build with linux/arm5

### ISSUE THREAD

**Issue by LipsonX** [ncruces/go-sqlite3#206]
Hi.

This problem come from [gitea](https://github.com/go-gitea/gitea/issues/32907). And I finally find out that it's sqlites library problems. see flow:

Step:
1. create a go [demo](https://pkg.go.dev/github.com/ncruces/go-sqlite3#example-package) with [go-sqlite3 v0.21.3](https://github.com/ncruces/go-sqlite3/releases/tag/v0.21.3). Open db by a file. eg. `db, err := sqlite3.Open("./mydb.sqlite3")`
2. All are well in Ubuntu20.04 amd64. it can create a file and write and read.
3. build by `GOOS=linux CGO_ENABLED=0 GOARM=5 GOARCH=arm go build ` and copy binary into `Linux 2.6.36.4brcmarm armv7l` deivce
4. run than can see: `2024/12/20 xx:xx:xx sqlite3: disk I/O error` (this happend after `db.Exec` or `db.QueryRow`)
5. If I change open by memery, then all is well. eg. `db, err := sqlite3.Open(":memory:")`

is’t really no support `Linux 2.6.36.4brcmarm armv7l`? it's seems like some incompatibility with this file system? any help?

**Comment by ncruces** [comment]
On Linux this library uses [OFD locks](https://github.com/ncruces/go-sqlite3/blob/main/vfs/README.md#file-locking) which were introduced in [Linux 3.15](https://man7.org/linux/man-pages/man2/fcntl.2.html#:~:text=Open%20file%20description%20locks%20(non%2DPOSIX)).

As an alternative, you can try to compile using `-tags sqlite3_dotlk` (or `-tags sqlite3_flock`).

> [!CAUTION]
> While those configurations should be safe on Linux **for single process use**, accessing the same databases concurrently with other processes (the `sqlite3` shell, backup solutions like Litestream, `sqlite3_rsync`, etc) will corrupt your data.

**Comment by LipsonX** [comment]
thanks bro. this does work. and thanks your amention.
