### ISSUE TITLE
FTS5 support?

### ISSUE THREAD

**Issue by Danlock** [ncruces/go-sqlite3#44]
Hello, I'm a fan of your work. I just used it to make a tiny CGO free CLI tool for image search at [searmage ](https://github.com/Danlock/searmage).

Are there any plans for adding support for the SQLite FTS5 extension?

**Comment by ncruces** [comment]
It should be [enabled](https://github.com/ncruces/go-sqlite3/tree/main/embed) (also [this](https://github.com/ncruces/go-sqlite3/blob/7bbd4f1e3c0dc736adddf1c1f39daa22da0ad273/sqlite3/sqlite_cfg.h#L74)), but I've not tested it. Is anything specific not working?

**Comment by Danlock** [comment]
Oh wow, fantastic. I assumed since mattn/go-sqlite3 requires a build tag to compile it in, it would have been in the ext folder.

It may be good to call that and JSON support in the README.md so it's easier to find for people making a quick comparison to mattn/go-sqlite3.

Thanks for the quick reply!

**Comment by ncruces** [comment]
OK, I'll review the copy on the main README.

I'm curious about the NUL panic. That likely indicates a place where you passed a “big string” where I was expecting a “small string.”

For most strings, we I use known length APIs that have no limit. Some APIs require NUL termination (e.g. file names?) and I use limits to avoid pointless copies of MB/GBs worth of data.

I may have borked something with too low a limit.

**Comment by Danlock** [comment]
The specific issue there was this query `SELECT path FROM images WHERE path IN array(?)` while I was using the array extension.

[This was the guilty function.](https://github.com/Danlock/searmage/commit/b5cda984db9ddf1064e6328746b558b46a2d3450#diff-30c25f2a7d8ae335d2aada4b0a6013ad9d159595bb6a2a14b1d0022451b6753fR31)

I probably was using the array extension improperly. But on the other hand that package only has an example for using it with the database/sql driver's, instead of the direct SQLite API.

**Comment by ncruces** [comment]
> I assumed since mattn/go-sqlite3 requires a build tag to compile it in, it would have been in the ext folder.

To document the rational behind this: in 2023, WASM doesn't really support dynamic linking, so “native” (implemented in C, or maybe C++/Rust/etc) extensions all need to be statically linked, and bundled into a single WASM blob. Thus, there is little reason to push them to a separate package (unless the WASM becomes unwieldy large).

I've (mostly) bundled everything that I considered useful from SQLite excluding things I can easily implement in Go (like Unicode), also to avoid mixing licenses (SQLite is public domain).

Larger native extensions under different terms would  need a separate package, but might become multiply incompatible (matrix of features) so I'd rather avoid that if at all possible.

Things that I do consider I can easily (or should/must) rewrite in Go, are being done bit-by-bit as extensions (there's a ToDo there).

**Comment by Danlock** [comment]
Thanks for the clarification. All I really needed was unicode, FTS5 and array so those bundling decisions make sense to me. Also it seems like SQLite bundles in FTS5 by default now, so that makes even more sense.
