### ISSUE TITLE
Move UUID from C to Go

### ISSUE THREAD

**Issue by ncruces** [ncruces/go-sqlite3#99]
Be as compatible with [uuid.c](https://github.com/sqlite/sqlite/blob/master/ext/misc/uuid.c) as possible. But support new UUID formats.

https://pkg.go.dev/github.com/google/uuid

**Comment by suyash-sneo** [comment]
Hi @ncruces. New here to OSS. I'd like to take this up and make my first contribution.

**Comment by ncruces** [comment]
That's great!

I'm looking for these 3 functions (more docs [here](https://github.com/sqlite/sqlite/blob/master/ext/misc/uuid.c)):
```
uuid()        - generate a version 4 UUID as a string
uuid_str(X)   - convert a UUID X into a well-formed UUID string
uuid_blob(X)  - convert a UUID X into a 16-byte blob
```

For parsing I'm fine with just using [`Parse`](https://pkg.go.dev/github.com/google/uuid#Parse) (no need to be exactly 100% compatible with the C version).

Then I'd like to (somehow) overload the `uuid()` to generate other kinds of UUIDs. Particularly V7, maybe just `uuid(7)`. But other kinds would be good.

These should be helpful to get you started:
- the Unicode [package](https://github.com/ncruces/go-sqlite3/tree/main/ext/unicode)
- the `CreateFunction` [example](https://github.com/ncruces/go-sqlite3/blob/37196923494df1825129cbb62147c3a462a076cc/func_test.go#L63)

**Comment by suyash-sneo** [comment]
Thanks!!
But I've never contributed to Open source and this repo doesn't have any guidelines that I could see.
Could you maybe provide a hint in the right direction?
That'll be super helpful

**Comment by ncruces** [comment]
Well, I'm not sure I can help much with that part except point to docs:
https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project

**Comment by suyash-sneo** [comment]
Sure, I'll refer to that. The material you have shared should help me get started so thanks for the help :)

**Comment by ncruces** [comment]
Removing the current `uuid` function and making it an extension is a minor breaking change.

I'd like to bundle it with #111 (another minor breaking change) before the next release.
